//Teste de Requisições REST - campanhas
@baseURL = http://localhost:4000
@titulo = Todos contra a fome
###
// GET - Lista todas as campanhas
GET {{baseURL}}/campanhas
Content-Type: application/json

###
// GET - Lista apenas uma campanha pelo titulo
GET {{baseURL}}/campanhas/{{titulo}}
Content-Type: application/json

###
// POST - Inclui uma nova campanha
POST {{baseURL}}/campanhas
Content-Type: application/json

{
   "titulo":"Todos contra a fome",
   "sobre" : "Campanha para arrecadar alimentos para famílias que precisam",
   "dataInicio": "2019-04-28T14:45:19",
   "dataTermino": "2019-04-26T14:45:15",
   "endereco" : "Rua Helena, 147",
   "categoria": "Alimentos",
   "observacoes": "Alimentos não pereciveis ou kit de cesta básica",
   "linkFoto": "https://unsplash.com/photos/Yn0l7uwBrpw ",
   "numero": "12345-67889",
   "voluntarios": "Sim",
   "descricaoAtividades": "Ajudar a embalar e transportar os alimentos"
}

### 
// DELETE - Apaga uma campanha através do titulo informado
DELETE {{baseURL}}/campanhas/{{titulo}}
Content-Type: application/json

###
// PUT - Altera uma campanha pelo titulo
PUT {{baseURL}}/campanhas/
Content-Type: application/json

{
   "titulo":"Todos contra a fome",
   "sobre" : "Campanha para arrecadar alimentos para todos que precisam",
   "dataInicio": "2019-04-28T14:45:19",
   "dataTermino": "2019-04-26T14:45:15",
   "endereco" : "Rua Helena, 147",
   "categoria": "Alimentos",
   "observacoes": "Alimentos não pereciveis ou kit de cesta básica",
   "linkFoto": "https://unsplash.com/photos/Yn0l7uwBrpw ",
   "numero": "12345-67889",
   "voluntarios": "Sim",
   "descricaoAtividades": "Ajudar a embalar e transportar os alimentos"
}
